name: Create and send a schedule


on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 8 AM Taipei (0 UTC)
  workflow_dispatch:

jobs:
  create-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install R Packages
        uses: r-lib/actions/setup-r-dependencies@v2


      # Step 1: retrieve emails from google
      - name: Get emails
        env: 
          GOOGLE_APP_PASSWORD: ${{ secrets.GOOGLE_APP_PASSWORD }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
          GOOGLE_OAUTH_REFRESH_TOKEN: ${{ secrets.GOOGLE_OAUTH_REFRESH_TOKEN }}
        run: |
          # echo skipping email downloading step for time
          python3 01-get_all_emails.py

      # Step 2: Process emails
      - name: Process emails
        run: |
          Rscript -e 'source("02-process_airbnb_emails.R")'

      # Step 3: Create daily schedule from emails
      # Step 4: Create a payment schedule
      - name: Create schedules
        run: Rscript -e 'source("03-create_daily_schedule.R"); source("04-create_payment_schedule.R")'
        

      # Step 5: Upload daily schedule to google drive
      - name: Upload schedule
        env: 
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
          GOOGLE_OAUTH_REFRESH_TOKEN: ${{ secrets.GOOGLE_OAUTH_REFRESH_TOKEN }}
        run: python3 05-upload_schedule_to_drive.py
        
      # Step 6: Send Line message
      - name: Send Line Message
        env: 
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        run: python3 06-send_line_message.py

